// src/App.tsx
import {Button, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Typography} from "@mui/material";
import {Box} from "@mui/system";
import axios, {AxiosResponse} from "axios";
import {useEffect, useState} from "react";
import moment from "moment";

const App = () => {
    const persons = [
        "2008UENO01", "2009OLSO01", "2011HOFF02", "2011RHEI01", "2012ITOR01",
        "2013FERT01", "2013GALA04", "2013KOBA01", "2015FIRM01", "2015GOWT01",
        "2015KUCA01", "2015MATT05", "2015MOHA10", "2015ROBI04", "2015TAKA05",
        "2016MORA24", "2016YENC01", "2017HONG17", "2017PALI04", "2017SZYS01",
        "2018PIKE01", "2018VASY01", "2009LIUE01", "2009YAUR01", "2007VALK01",
        "2010HULL01", "2010UTOM01", "2010WUIF01", "2012BEAH01", "2012GONZ10",
        "2012MCNE01", "2013WANG67", "2014CZAP01", "2014LEES01", "2014RAJE03",
        "2014VORL01", "2014WENW01", "2014YELI01", "2014ZAKR01", "2015CHNG01",
        "2015GROH02", "2015KOVA07", "2015OAKK01", "2015RAOJ01", "2015SING22",
        "2015STAU01", "2015WANG09", "2016KOLA02", "2016MART29", "2016MELN01",
        "2016NUNE11", "2017HUAN77", "2017KIRB01", "2015LEEJ12", "2015LEON02",
        "2018BERE01", "2017TRAN25", "2015MINK04", "2015CHER07", "2013RIGO01",
        "2018MURR03", "2017ENGB01", "2018NGHA02", "2016CHOI01", "2017SANK04",
        "2013JOHN10", "2017CHAM09", "2021DUNA01", "2016BARO04", "2016PFEI01",
        "2016BITZ01"
    ]
    const URL = "https://www.worldcubeassociation.org/api/v0/persons?per_page=100&wca_ids="

    const [personsData, setPersonsData] = useState(Array<PersonsData>())

    interface PersonsData {
        name: string,
        single: number,
        average: number
    }

    enum SortType {
        SINGLE,
        AVERAGE
    }

    useEffect(() => {
        fetchPersonsData()
    }, [])

    const fetchPersonsData = () => {
        axios
            .get(URL + persons.join(","))
            .then((response: AxiosResponse<Array<any>>) => {
                const data: Array<PersonsData> = response.data.map((item: any) => ({
                    name: item.person.name as string,
                    single: item.personal_records["555"].single.best as number,
                    average: item.personal_records["555"].average.best as number
                }))
                setPersonsData(getSortedResult(data, SortType.AVERAGE))
            })
    }

    const getSortedResult = (data: Array<PersonsData>, sortType: SortType): Array<PersonsData> => {
        const dataTmp = data.slice()
        switch (sortType) {
            case SortType.SINGLE: {
                dataTmp.sort((a: PersonsData, b: PersonsData) => a.single - b.single)
                break
            }
            case SortType.AVERAGE: {
                dataTmp.sort((a: PersonsData, b: PersonsData) => a.average - b.average)
                break
            }
            default: {
                break
            }
        }
        return dataTmp
    }

    const handleSingleSortClick = () => {
        setPersonsData(getSortedResult(personsData, SortType.SINGLE))
    }

    const handleAverageSortClick = () => {
        setPersonsData(getSortedResult(personsData, SortType.AVERAGE))
    }

    const getFormattedTime = (milliSec: number): string => {
        if (milliSec > 60000) {
            return moment(milliSec).format("m:ss.SS")
        } else {
            return moment(milliSec).format("ss.SS")
        }
    }

    return (
        <Box
            display={"flex"}
            justifyContent={"center"}
            flexDirection={"column"}
            sx={{
                margin: '0 auto',
                maxWidth: '700px'
            }}
        >
            <Box
                display={"flex"}
                justifyContent={"center"}
                sx={{
                    padding: "20px"
                }}
            >
                <Typography variant={"h3"}>5x5 Yau Ranking</Typography>
            </Box>
            <Box display={"flex"} justifyContent={"center"}>
                <TableContainer>
                    <Table>
                        <TableHead>
                            <TableRow>
                                <TableCell />
                                <TableCell />
                                <TableCell align={"center"}>
                                    <Button variant={"contained"} onClick={handleSingleSortClick}>
                                        Sort
                                    </Button>
                                </TableCell>
                                <TableCell align={"center"}>
                                    <Button variant={"contained"} onClick={handleAverageSortClick}>
                                        Sort
                                    </Button>
                                </TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell align={"center"}>Rank</TableCell>
                                <TableCell align={"center"}>Name</TableCell>
                                <TableCell align={"center"}>Single</TableCell>
                                <TableCell align={"center"}>Average</TableCell>
                            </TableRow>
                        </TableHead>
                        <TableBody>
                            {personsData.map((item, index) =>
                                <TableRow key={index}>
                                    <TableCell align={"center"}>{index + 1}</TableCell>
                                    <TableCell align={"center"}>{item.name}</TableCell>
                                    <TableCell align={"center"}>{getFormattedTime(item.single * 10)}</TableCell>
                                    <TableCell align={"center"}>{getFormattedTime(item.average * 10)}</TableCell>
                                </TableRow>
                            )}
                        </TableBody>
                    </Table>
                </TableContainer>
            </Box>
        </Box>
    )

}

export default App;

// src/App.vue
<template>
  <div id="app">
    <h2>5x5 Yau Ranking</h2>
    <br>
    <v-simple-table>
      <template>
        <thead>
        <tr>
          <th></th>
          <th></th>
          <th>
            <v-btn elevation="2" @click="doSort('single')">sort</v-btn>
          </th>
          <th>
            <v-btn elevation="2" @click="doSort('average')">sort</v-btn>
          </th>
        </tr>
        <tr>
          <th>Rank</th>
          <th>Name</th>
          <th>Single</th>
          <th>Average</th>
        </tr>
        </thead>
        <tbody>
        <tr v-for="(item, index) of result" :key="item">
          <td>{{ index + 1 }}</td>
          <td>{{ item[0] }}</td>
          <td>{{ item[1] }}</td>
          <td>{{ item[2] }}</td>
        </tr>
        </tbody>
      </template>
    </v-simple-table>
  </div>
</template>

<script>
export default {
  name: 'App',
  data: function () {
    return {
      result: [],
      persons: [
        "2008UENO01", "2009OLSO01", "2011HOFF02", "2011RHEI01", "2012ITOR01",
        "2013FERT01", "2013GALA04", "2013KOBA01", "2015FIRM01", "2015GOWT01",
        "2015KUCA01", "2015MATT05", "2015MOHA10", "2015ROBI04", "2015TAKA05",
        "2016MORA24", "2016YENC01", "2017HONG17", "2017PALI04", "2017SZYS01",
        "2018PIKE01", "2018VASY01", "2009LIUE01", "2009YAUR01", "2007VALK01",
        "2010HULL01", "2010UTOM01", "2010WUIF01", "2012BEAH01", "2012GONZ10",
        "2012MCNE01", "2013WANG67", "2014CZAP01", "2014LEES01", "2014RAJE03",
        "2014VORL01", "2014WENW01", "2014YELI01", "2014ZAKR01", "2015CHNG01",
        "2015GROH02", "2015KOVA07", "2015OAKK01", "2015RAOJ01", "2015SING22",
        "2015STAU01", "2015WANG09", "2016KOLA02", "2016MART29", "2016MELN01",
        "2016NUNE11", "2017HUAN77", "2017KIRB01", "2015LEEJ12", "2015LEON02",
        "2018BERE01", "2017TRAN25", "2015MINK04", "2015CHER07", "2013RIGO01",
        "2018MURR03", "2017ENGB01"
      ]
    }
  },
  mounted: function () {
    this.getData();
  },
  methods: {
    getData: function () {
      let url = "https://www.worldcubeassociation.org/api/v0/persons?per_page=100&wca_ids=" + this.persons[0];
      for (let i = 1; i < this.persons.length; i++) {
        url += "," + this.persons[i]
      }
      this.axios.get(url)
          .then((response) => {
            const data = [];
            for (let i = 0; i < response.data.length; i++) {
              data.push([response.data[i].person.name,
                this.timeToFloat(response.data[i].personal_records["555"].single.best),
                this.timeToFloat(response.data[i].personal_records["555"].average.best)]);
            }
            this.result = data;
            this.doSort("average");
          })
          .catch((e) => {
            console.log(e);
          })
    },
    doSort: function (sortType) {
      if (sortType === "single") {
        this.result.sort(function (a, b) {
          return a[1] - b[1];
        });
      } else if (sortType === "average") {
        this.result.sort(function (a, b) {
          return a[2] - b[2];
        });
      }
    },
    timeToFloat: function (time) {
      if (parseInt(time) % 100 === 0) {
        return parseInt(time) / 100 + ".00";
      } else if (parseInt(time) % 10 === 0) {
        return parseInt(time) / 100 + "0";
      } else {
        return parseInt(time) / 100;
      }
    }
  }
}
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
